# Generated by Django 2.2 on 2020-07-01 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_compra',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_compra', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('cursos', models.ManyToManyField(blank=True, to='cursos.Curso')),
            ],
        ),
    ]
